# Generated by Django 4.2.1 on 2023-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rate_brand_rating_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(related_name='products', to='app.brand'),
        ),
    ]
