# Generated by Django 4.2.1 on 2023-05-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_brand_product_product_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.DeleteModel(
            name='Holder',
        ),
        migrations.AddField(
            model_name='save_information',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_information', to='app.brand'),
        ),
        migrations.AddField(
            model_name='save_information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='app.product'),
        ),
    ]
